const URLS = {
  intro: 'www.intro.webm',
  gardenSalad:'www.gardenSalad.webm',
  friedChicken:'www.friedChicken.webm',
  grilledCheese:'www.grilledCheese.webm',
  blt:'www.blt.webm',
  hamburger:'www.hamburger.webm',
  dressing:'www.dressing.webm',
  ranch:'www.ranch.webm',
  balsamic:'www.balsamic.webm',
  thousandIsland:'www.thousandIsland.webm',
  bleuCheese:'www.wheat.webm',
  bread:'www.bread.webm',
  wheat:'www.wheat.webm',
  white:'www.white.webm',
  cheese:'www.cheese.webm',
  yesCheese: 'www.yesCheese.webm',
  noCheese: 'www.noCheese.webm',
  yesEverything: 'www.yesEverything.webm',
  noEverything: 'www.noEverything.webm',
  sideDish:'www.sidedish.webm',
  mashedPotatoes:'www.mashedPotatoes.webm',
  fries:'www.fries.webm',
  sideSalad:'www.sideSalad.webm',
  coleSlaw:'www.coleSlaw.webm',
  fruit:'www.fruit.webm',
  finale:'www.finale.webm',
}

export default URLS;